version: "3.8"

services:
  web:
    build: 
      context: .
    container_name: phx_partner
    restart: unless-stopped
    command: sh ./start.sh
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db_phx
    networks:
      - phxnet

  db_phx:
    image: 'postgres:13'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - phxnet

volumes:
  postgres:

networks:
  phxnet:
    name: phxnet
