version: "3"
services:
  db_phx:
    image: 'postgres:13'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - phxnet

  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/phx_partner
    ports:
      - "4000:4000"
    links:
      - db_phx
    depends_on:
      - db_phx
    networks:
      - phxnet

volumes:
  postgres:

networks:
  phxnet:
    name: phxnet
